

  - apt: name=cups

  - service: name=cups state=started

  - shell: lpstat -p | grep -q {{printer.name}}
    register: have_printer
    ignore_errors: yes
    changed_when: "have_printer.rc != 0"

  # TODO better paths?
  - copy: src={{printer.ppd}} dest=/tmp

  - shell: |
      # install
      lpadmin \
        -p '{{printer.name}}' \
        -v '{{printer.url}}' \
        -P '/tmp/{{printer.ppd}}' \
        -E
      # set default
      lpadmin -d {{printer.name}}
    when: "have_printer.rc != 0"


