
  # TODO maybe parametize
  # NOTE the symbolic-link /var/lib/tomcat7/conf -> /etc/tomcat7


  # TODO maybe move into the node definition
  # port forward to tomcat7
  - apt: name=iptables-persistent
  - blockinfile:
      dest: /etc/iptables-rules
      create: true
      content: |
        # deployed by ansible!
        iptables -t nat --flush
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
    notify: reconfigure-iptables

  - apt: name=tomcat7 update_cache=yes

  - set_fact: tomcat7=/var/lib/tomcat7
  - set_fact: conf={{tomcat7}}/conf
  - set_fact: webapps={{tomcat7}}/webapps
  - set_fact: overrides={{conf}}/overrides
  - set_fact: geonetwork_data={{conf}}/geonetwork_data
  - set_fact: config={{geonetwork_data}}/config
  - set_fact: aodn_schema_plugins={{conf}}/aodn-schema-plugins
  - set_fact: schema_plugins={{config}}/schema_plugins
  - set_fact: codelist={{config}}/codelist
  - set_fact: geonetwork={{webapps}}/geonetwork


  # TODO change this to use with_items

  - file: path={{tomcat7}}          state=directory owner=tomcat7 group=tomcat7
  # - file: path={{conf}}             state=directory owner=tomcat7 group=tomcat7  # it's a symbolic link
  - file: path={{webapps}}          state=directory owner=tomcat7 group=tomcat7
  - file: path={{overrides}}        state=directory owner=tomcat7 group=tomcat7
  - file: path={{geonetwork_data}}  state=directory owner=tomcat7 group=tomcat7
  - file: path={{config}}           state=directory owner=tomcat7 group=tomcat7
  # - file: path={{aodn_schema_plugins}} state=directory owner=tomcat7 group=tomcat7
  - file: path={{schema_plugins}}   state=directory owner=tomcat7 group=tomcat7 recurse=yes
  # - file: path={{codelist}}         state=directory owner=tomcat7 group=tomcat7 recurse=yes should be done after git?
  - file: path={{geonetwork}}         state=directory owner=tomcat7 group=tomcat7 recurse=yes  # must create


  # jndi
  - template: src=context.j2 dest={{conf}}/context.xml owner=tomcat7 group=tomcat7
    notify: restart-tomcat7

  # tomcat opts
  # TODO maybe remove config-conf/overrides from here, and instead define in context.xml
  - template: src=tomcat7.j2 dest=/etc/default/tomcat7 owner=tomcat7 group=tomcat7
    notify: restart-tomcat7


  # overrides
  - file: path={{overrides}} state=directory owner=tomcat7
  - template: src=config-overrides.j2 dest={{overrides}}/config-overrides.xml owner=tomcat7 group=tomcat7
  - template: src=log4j-overrides.j2  dest={{overrides}}/log4j-overrides.xml  owner=tomcat7 group=tomcat7


  # war
  # TODO make war source configurable
  - get_url: >
      url=https://jenkins.aodn.org.au/job/geonetwork_prod/lastSuccessfulBuild/artifact/web/target/geonetwork.war
      dest={{webapps}}/geonetwork.war
    notify: restart-tomcat7


  # Unpack war to make iso19139 available
  - apt: name=unzip
  - file: path={{geonetwork}} state=directory
  - unarchive: src={{webapps}}/geonetwork.war dest={{geonetwork}} copy=no
  - file: path={{geonetwork}} owner=tomcat7 group=tomcat7 recurse=yes


  # Schema plugins
  # https://github.com/ansible/ansible/issues/7474
  - shell: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts creates=/etc/ssh/ssh_known_hosts
  - git: repo=https://github.com/aodn/schema-plugins  dest={{aodn_schema_plugins}} version=master # # master  version=merge-imos-to-2.10.x
    notify: restart-tomcat7
  - file: path={{aodn_schema_plugins}} state=directory owner=tomcat7 group=tomcat7

  # Only link needed schema-plugins
  - file: >
      src={{geonetwork}}/WEB-INF/data/config/schema_plugins/iso19139
      dest={{schema_plugins}}/iso19139
      state=link owner=tomcat7 group=tomcat7

  - file: src={{aodn_schema_plugins}}/iso19139.mcp     dest={{schema_plugins}}/iso19139.mcp      state=link owner=tomcat7 group=tomcat7
  - file: src={{aodn_schema_plugins}}/iso19139.mcp-2.0 dest={{schema_plugins}}/iso19139.mcp-2.0  state=link owner=tomcat7 group=tomcat7
  - file: src={{aodn_schema_plugins}}/iso19139.anzlic  dest={{schema_plugins}}/iso19139.anzlic   state=link owner=tomcat7 group=tomcat7
  - file: src={{aodn_schema_plugins}}/iso19135         dest={{schema_plugins}}/iso19135          state=link owner=tomcat7 group=tomcat7


  # codelists
  - git: repo=https://github.com/aodn/codelist dest={{codelist}} version=master force=yes
  - file: path={{codelist}} owner=tomcat7 group=tomcat7 recurse=yes

