
  # check for database
  - shell: psql -tAc "select 1 from pg_database where datname='geonetwork'"
    become: yes
    become_user: postgres
    register: have_db
    changed_when: false


  # communication is actually kind of horrid
  # copy db from host
  - copy: src=gn.dump dest=/tmp

  # restore the db and hack an admin, admin account
  - name: Restore Geonetwork db
    shell: "{{item}}"
    become: yes
    become_user: postgres
    with_items:
      - |
        psql -d postgres -c "
          drop user if exists geonetwork;
          create user geonetwork password 'geonetwork';
          "
      - pg_restore -d postgres -x -C /tmp/gn.dump
      - |
        psql -d geonetwork -c "
          update users
          set password='46e44386069f7cf0d4f2a420b9a2383a612f316e2024b0fe84052b0b96c479a23e8a0be8b90fb8c2'
          where name='admin'
          "
    when: have_db.stdout != "1"
    # when: false


