
# TODO - add the bash aliases as template argument?
# actually want option of dotfiles

# should be moved out of common... and be explicit...

  - user: name="{{item.name}}" groups="{{item.group}}" shell=/bin/bash append=yes
    with_items: users

  - authorized_key: user="{{item.name}}" key="{{item.pubkey}}"
    with_items: users
