
    # x11-apps libxml2-utils net-tools curl
    # Common tools
    - apt: name=vim
    # - apt: name=git
    - apt: name=screen
    - apt: name=less
    - apt: name=aptitude
    - apt: name=mlocate
    - apt: name=wget
    - apt: name=curl
    - apt: name=dnsutils   # dig, nslookup
    - apt: name=sudo
      # - apt: name=nettools
    - apt: name=time
    - apt: name=psmisc    # pstree
    - apt: name=iftop
    - apt: name=iotop
    - apt: name=lsof   # or fuser
    - apt: name=iptables
    - apt: name=netcat-traditional
    # - apt: name=debootstrap
    # - apt: name=sshfs  # container doesn't like
    - apt: name=rsync
    - apt: name=arp-scan
    - apt: name=tcpdump

    - apt: name=libxml2-utils

