

  # jdk_deploy_path is set in ./plays/jdk.yml

  - apt: name=curl

  - file:
      path: "{{jdk_deploy_path}}"
      state: directory

  - shell: "{{item}}"
    args:
      chdir: "{{jdk_deploy_path}}"
      creates: jdk-7u80-linux-x64.tar.gz
    with_items:
      - >
        curl -L -H 'Cookie:oraclelicense=accept-securebackup-cookie'
        http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
        -o jdk-7u80-linux-x64.tar.gz


#  - unarchive:
#      src: "{{jdk_deploy_path}}/jdk-7u80-linux-x64.tar.gz"
#      dest: "{{jdk_deploy_path}}"
#
#

