


  - copy:
      backup: yes
      dest: /etc/motd
      content: |
        # deployed by ansible!

  - copy:
      backup: yes
      dest: /etc/ssh/sshd_config
      content: |
        # deployed by ansible!
        Port 22
        Protocol 2
        HostKey /etc/ssh/ssh_host_rsa_key
        HostKey /etc/ssh/ssh_host_dsa_key
        HostKey /etc/ssh/ssh_host_ecdsa_key
        HostKey /etc/ssh/ssh_host_ed25519_key
        UsePrivilegeSeparation yes

        KeyRegenerationInterval 3600
        ServerKeyBits 1024

        SyslogFacility AUTH
        LogLevel INFO

        LoginGraceTime 30
        # JA
        PermitRootLogin no
        StrictModes yes

        RSAAuthentication yes
        PubkeyAuthentication yes

        IgnoreRhosts yes
        RhostsRSAAuthentication no

        IgnoreRhosts yes
        RhostsRSAAuthentication no
        HostbasedAuthentication no

        PermitEmptyPasswords no
        ChallengeResponseAuthentication no

        # JA the important bit
        PasswordAuthentication no

        X11Forwarding yes
        X11DisplayOffset 10
        PrintMotd no
        PrintLastLog yes
        TCPKeepAlive yes

        # banner is before login, motd is after
        # JA changed
        PrintMotd yes
        # Banner /etc/issue.net

        AcceptEnv LANG LC_*

        Subsystem sftp /usr/lib/openssh/sftp-server

        UsePAM yes

    notify: restart-sshd



